name: Run tests on merge

on:
  push:
    branches:
      - main  

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (flex, bison, gcc)
        run: |
          sudo apt update
          sudo apt install -y flex bison gcc libfl-dev

      - name: Make script executable
        run: chmod +x ./run_w_steroids.sh 

      - name: Run Assignments test
        run: ./run_w_steroids.sh -f "assignments.txt"

      - name: Run logical operators test
        run: ./run_w_steroids.sh -f "logical_operators.txt"

      - name: Run variable declaration test
        run: ./run_w_steroids.sh -f "variable_declaration.txt"
